### ISSUE TITLE
View project wiki button

### ISSUE THREAD

**Issue by MatthewNobes** [MatthewNobes/MatthewNobes.github.io#13]
Add a view project wiki button that allows the user to open the wiki for a project in a new tab.

**Comment by ayush-chandil** [comment]
can you please assign me this issue?

**Comment by MatthewNobes** [comment]
@ayush-chandil Sorry I prefer to keep this repository for myself as it is my personal website

**Comment by MatthewNobes** [comment]
Wiki button created and tests are passing
